app/main/models.py
#!/usr/bin/env python
# coding: utf-8

from .. import db


class GitProject(db.Model):
    __tablename__ = 'gitproject'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), index=True)
    addr = db.Column(db.String(80), unique=True)
    des = db.Column(db.String(160), default=False)

    def __repr__(self):
        return '<GitProject %r>' % self.name

app/__init__.py
#!/usr/bin/env python
# coding: utf-8

import click
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from setting import config


bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name=None):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)

    from main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    click.echo('You got me.')
    return app

app/main/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint

main = Blueprint('main', __name__)

import views

app/main/views.py
#!/usr/bin/env python
# coding: utf-8

import os
from flask import current_app, render_template, redirect, url_for, flash, send_file
from . import main
from utils import is_folder, Ofile
from .. import db
from .models import *


@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html')


@main.route('/showone', defaults={'name': ''})
@main.route('/showone/<path:name>', methods=['GET', 'POST'])
def showone(name):
    fpath = current_app.config['FILE_DIR']
    full_path = os.path.join(fpath, name)
    if not is_folder(full_path):
        return send_file(full_path)
    file_list = []
    file_names = os.listdir(full_path)
    for f in file_names:
        fo = Ofile(fpath, name, f)
        file_list.append(fo)
    return render_template('showfiles.html', file_list=file_list)


@main.route('/projects', methods=['GET', 'POST'])
def projects():
    db
    return render_template('projects.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}BridgeL{% endblock %}

{% block head %}
{{ super() }}
<link rel="icon" href="{{ url_for('static', filename='sanguo.png') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse container">
        <div class="navbar-header"> <a class="navbar-brand" href="{{ url_for('main.index') }}">BridgeL</a> </div>
        <ul class="nav navbar-nav pull-left">
                <li><a class="btn" href="{{ url_for('main.projects') }}">项目管理</a></li>
                <li><a class="btn" href="{{ url_for('main.showone') }}">文件下载</a></li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        <!-- flash message -->
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">close</span></button>
            {{ message }}
        </div>
        {% endfor %}

        <!-- body block -->
        {% block page_content %} {% endblock %}
    </div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>INDEX</title>
</head>
<body>
<p>Hello world!</p>
</body>
</html>

app/templates/projects.html
{% extends 'base.html' %}

{% block page_content %}
<p> Welcome to 项目管理!</p>
{% endblock %}

app/templates/showfiles.html
{% extends 'base.html' %}

{% block page_content %}
<ul class="list-group">
{% for filename in file_list%}
    <a class="list-group-item" href="{{ url_for('main.showone', name=filename.path_to_father)}}">{{ filename.name }}</a>
{% endfor %}
</ul>

{% endblock %}